/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset */
        get: operations["get_dataset_api_dataset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Dataset */
        post: operations["reset_dataset_api_dataset_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Dataset */
        post: operations["upload_dataset_api_dataset_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/audio/{intent}.mp3": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Audio */
        get: operations["demo_audio_api_demo_audio__intent__mp3_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_api_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/turns/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Turn */
        get: operations["latest_turn_api_turns_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Voice Session */
        get: operations["voice_session_api_voice_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Completions */
        post: operations["chat_completions_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Anomaly
         * @description Flat shape; which optional fields are set depends on `type`.
         *
         *     new_recurring      merchants, category, count, total
         *     duplicate_charge   merchants, count, amount, total
         *     amount_drift       merchants, amount, previous_amount, change_pct
         *     missing_recurring  merchants, amount
         *     category_outlier   category, amount, typical_amount, change_pct
         *     large_transaction  merchants, category, amount
         */
        Anomaly: {
            /** Amount */
            amount?: number | null;
            /** Category */
            category?: string | null;
            /** Change Pct */
            change_pct?: number | null;
            /** Count */
            count?: number | null;
            /** Merchants */
            merchants?: string[];
            /** Previous Amount */
            previous_amount?: number | null;
            /** Total */
            total?: number | null;
            type: components["schemas"]["AnomalyType"];
            /** Typical Amount */
            typical_amount?: number | null;
        };
        /**
         * AnomalyType
         * @enum {string}
         */
        AnomalyType: "new_recurring" | "duplicate_charge" | "amount_drift" | "missing_recurring" | "category_outlier" | "large_transaction";
        /** ApiError */
        ApiError: {
            code: components["schemas"]["ErrorCode"];
            /** Details */
            details?: string[];
            /** Message */
            message: string;
        };
        /** Body_upload_dataset_api_dataset_upload_post */
        Body_upload_dataset_api_dataset_upload_post: {
            /** File */
            file: string;
        };
        /** CategoryAmount */
        CategoryAmount: {
            /** Amount */
            amount: number;
            /** Delta Pct */
            delta_pct?: number | null;
            /** Name */
            name: string;
        };
        /**
         * Channel
         * @enum {string}
         */
        Channel: "text" | "voice";
        /** ChatCompletionRequest */
        ChatCompletionRequest: {
            /** Max Tokens */
            max_tokens?: number | null;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /** Model */
            model?: string | null;
            /**
             * Stream
             * @default false
             */
            stream: boolean;
            /** Temperature */
            temperature?: number | null;
            /** User Id */
            user_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Content */
            content?: string | {
                [key: string]: unknown;
            }[] | null;
            /** Role */
            role: string;
        } & {
            [key: string]: unknown;
        };
        /** Comparison */
        Comparison: {
            biggest_decrease?: components["schemas"]["CategoryAmount"] | null;
            biggest_increase?: components["schemas"]["CategoryAmount"] | null;
            /** Current Total Out */
            current_total_out: number;
            /** Delta Pct */
            delta_pct: number;
            /** Prior Total Out */
            prior_total_out: number;
        };
        /** Context */
        Context: {
            /** Delta Pct */
            delta_pct: number;
            /** Month Total Out */
            month_total_out: number;
            /** Prior Month Total Out */
            prior_month_total_out: number;
        };
        /** DatasetInfo */
        DatasetInfo: {
            /** Current Period */
            current_period: string;
            /**
             * Date Max
             * Format: date
             */
            date_max: string;
            /**
             * Date Min
             * Format: date
             */
            date_min: string;
            /** Name */
            name: string;
            /** Row Count */
            row_count: number;
            /**
             * Source
             * @enum {string}
             */
            source: "fixture" | "upload";
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "invalid_request" | "csv_invalid" | "dataset_empty" | "narration_failed" | "unauthorized" | "not_found" | "not_implemented";
        /** FactBundle */
        FactBundle: {
            /** Anomalies */
            anomalies?: components["schemas"]["Anomaly"][];
            comparison?: components["schemas"]["Comparison"] | null;
            context: components["schemas"]["Context"];
            /**
             * Contract Version
             * @default 2
             */
            contract_version: string;
            lookup?: components["schemas"]["Lookup"] | null;
            /**
             * Period
             * @example September 2026
             */
            period: string;
            plan?: components["schemas"]["QueryPlan"] | null;
            query_type: components["schemas"]["Intent"];
            summary?: components["schemas"]["MonthSummary"] | null;
            /**
             * Understood
             * @description Read-back of how the question was understood, set only when something was inferred or carried over from the previous question.
             * @example groceries in July
             */
            understood?: string | null;
            verdict: components["schemas"]["Verdict"];
        };
        /** GuardResult */
        GuardResult: {
            /** Attempts */
            attempts: number;
            /** Passed */
            passed: boolean;
            /** Rejected Tokens */
            rejected_tokens?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Contract Version
             * @default 2
             */
            contract_version: string;
            dataset?: components["schemas"]["DatasetInfo"] | null;
            /** Demo Mode */
            demo_mode: boolean;
            /**
             * Narrator
             * @enum {string}
             */
            narrator: "cloud" | "local" | "template";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Stub Mode */
            stub_mode: boolean;
        };
        /**
         * Intent
         * @enum {string}
         */
        Intent: "anomalies" | "month_summary" | "where_money_went" | "compare_last_month" | "lookup" | "replay" | "advice_refused" | "identity" | "help" | "unsupported" | "unknown";
        /** Latency */
        Latency: {
            /** Analysis */
            analysis: number;
            /** Narration */
            narration: number;
            /** Total */
            total: number;
        };
        /**
         * Lookup
         * @description Result of executing a QueryPlan. Every figure computed by pandas.
         */
        Lookup: {
            /** Average */
            average?: number | null;
            /** Count */
            count: number;
            /** Delta Pct */
            delta_pct?: number | null;
            /**
             * Empty
             * @default false
             */
            empty: boolean;
            /** Items */
            items?: components["schemas"]["CategoryAmount"][];
            largest?: components["schemas"]["MerchantAmount"] | null;
            /** Period Label */
            period_label: string;
            /** Prior Label */
            prior_label?: string | null;
            /** Prior Total */
            prior_total?: number | null;
            /**
             * Subject Label
             * @example groceries
             * @example Kroger
             * @example everything
             */
            subject_label: string;
            /** Total */
            total: number;
        };
        /** MerchantAmount */
        MerchantAmount: {
            /** Amount */
            amount: number;
            /** Merchant */
            merchant: string;
        };
        /**
         * Metric
         * @enum {string}
         */
        Metric: "total_out" | "total_in" | "net" | "count" | "average" | "largest" | "smallest" | "list_recurring" | "top_merchants" | "top_categories" | "trend";
        /** MonthSummary */
        MonthSummary: {
            /** Net */
            net: number;
            /** Top Categories */
            top_categories?: components["schemas"]["CategoryAmount"][];
            /** Total In */
            total_in: number;
            /** Total Out */
            total_out: number;
        };
        /**
         * NarrationSource
         * @enum {string}
         */
        NarrationSource: "model" | "template" | "refusal" | "replay" | "cache";
        /** Period */
        Period: {
            /**
             * End
             * Format: date
             */
            end: string;
            /** @default this_month */
            kind: components["schemas"]["PeriodKind"];
            /**
             * Label
             * @example September 2026
             * @example the last 30 days
             */
            label: string;
            /**
             * Start
             * Format: date
             */
            start: string;
        };
        /**
         * PeriodKind
         * @enum {string}
         */
        PeriodKind: "this_month" | "last_month" | "named_month" | "last_n_days" | "this_week" | "last_week" | "this_year" | "all_time";
        /**
         * PlanSource
         * @enum {string}
         */
        PlanSource: "pattern" | "model" | "followup";
        /**
         * QueryPlan
         * @description The parsed question. Executed deterministically; no number originates here.
         */
        QueryPlan: {
            /** Limit */
            limit?: number | null;
            metric: components["schemas"]["Metric"];
            period: components["schemas"]["Period"];
            /** @default pattern */
            source: components["schemas"]["PlanSource"];
            subject?: components["schemas"]["Subject"];
        };
        /** QueryRequest */
        QueryRequest: {
            /** @default text */
            channel: components["schemas"]["Channel"];
            /**
             * Discreet
             * @default false
             */
            discreet: boolean;
            /** Text */
            text: string;
        };
        /**
         * SseEvent
         * @enum {string}
         */
        SseEvent: "turn" | "dataset" | "ping";
        /**
         * Subject
         * @description What the question is about. `value` is always a real category or merchant in the
         *     loaded ledger — the parser cannot invent one.
         */
        Subject: {
            /** @default all */
            kind: components["schemas"]["SubjectKind"];
            /** Value */
            value?: string | null;
        };
        /**
         * SubjectKind
         * @enum {string}
         */
        SubjectKind: "all" | "category" | "merchant";
        /** Turn */
        Turn: {
            /** Audio Url */
            audio_url?: string | null;
            channel: components["schemas"]["Channel"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            fact_bundle?: components["schemas"]["FactBundle"] | null;
            guard: components["schemas"]["GuardResult"];
            intent: components["schemas"]["Intent"];
            latency_ms: components["schemas"]["Latency"];
            /** Narration */
            narration: string;
            narration_source: components["schemas"]["NarrationSource"];
            /** Query Text */
            query_text: string;
            /** Turn Id */
            turn_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Verdict
         * @enum {string}
         */
        Verdict: "normal" | "normal_with_exception" | "unusual" | "no_data";
        /** VoiceSession */
        VoiceSession: {
            /** Agent Id */
            agent_id: string;
            /** Conversation Token */
            conversation_token?: string | null;
            /** Signed Url */
            signed_url?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_dataset_api_dataset_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetInfo"];
                };
            };
        };
    };
    reset_dataset_api_dataset_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetInfo"];
                };
            };
        };
    };
    upload_dataset_api_dataset_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_api_dataset_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetInfo"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    demo_audio_api_demo_audio__intent__mp3_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intent: components["schemas"]["Intent"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream. `event: turn` carries a Turn, `event: dataset` a DatasetInfo, `event: ping` is a keepalive every 15s. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    query_api_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Turn"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    latest_turn_api_turns_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Turn"];
                };
            };
            /** @description No turns yet */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    voice_session_api_voice_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceSession"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    chat_completions_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest"];
            };
        };
        responses: {
            /** @description chat.completion JSON, or an SSE stream of chat.completion.chunk objects ending in `data: [DONE]` when stream=true. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
